### ISSUE TITLE
Some questions about translation

### ISSUE THREAD

**Issue by JiquanWang99** [neon-bindings/website#223]
I want to translate the docs into Chinese, how should I do? In addition to translate the Markdown files, how to change the other file?

**Comment by dherman** [comment]
@JiquanWang99 We'd love to get your help with the translation! Which other files would you like help understanding? If it's easier, I'm happy to talk on our community Slack, too.

**Comment by amilajack** [comment]
As a tip, Docusarus has translation support for many languages. This should make the contribution a lot easier than having to manually translate everything.

https://docusaurus.io/blog/2021/03/09/releasing-docusaurus-i18n#translate-your-site. Let me know if this helps!

**Comment by JiquanWang99** [comment]
@amilajack Sure, I will try this. Thank you for your help.
