### ISSUE TITLE
Incorrect page title: "JSON"

### ISSUE THREAD

**Issue by joepie91** [neon-bindings/website#77]
The documentation at https://neon-bindings.com/docs/json has "JSON" as its title, but the contents of the page don't actually have anything to do with JSON (which is a separate language from JS entirely); rather, they're about serializing/deserializing JS data structures.

I'd suggest that "Data structures" is probably a better title for this page.

I'd create a PR, but unfortunately it seems that simply renaming `json.md` and its metadata will result in the original `https://neon-bindings.com/docs/json` URL breaking, and I'm not sure how redirects are handled in this setup.

**Comment by amilajack** [comment]
No worries! Submit the PR and I can add handle the URL issues.
