### ISSUE TITLE
Project homepage says "this recording has been archived" at the bottom for the asciinema thing

### ISSUE THREAD

**Issue by josephrocca** [neon-bindings/website#84]
The project homepage says "this recording has been archived" at the bottom for the asciinema thing.

**Comment by jeffvandyke** [comment]
Still does

**Comment by amilajack** [comment]
Duplicate of https://github.com/neon-bindings/website/issues/84

**Comment by jeffvandyke** [comment]
Uhh, what? The message says "Duplicate of #84", but this *is* issue 84... issue #408 is also marked as a duplicate of #84... something wierd's going on.

Also, the issue is still unfixed.
