### ISSUE TITLE
Broken link to Electron app guide

### ISSUE THREAD

**Issue by spenserblack** [neon-bindings/website#96]
In the [Hello World guide](https://neon-bindings.com/docs/hello-world), the link to the Electron app guide (3rd paragraph, last sentence), points to [this broken link](https://neon-bindings.com/electron-apps/). I think it's supposed to point [here](https://neon-bindings.com/docs/electron-apps).

**Comment by amilajack** [comment]
I can't reproduce this

**Comment by spenserblack** [comment]
Just checked again, looks like it's been fixed.
